# Dockerfile for stress-ng
#
FROM ubuntu:17.10
MAINTAINER  R. Melton
LABEL description="image which runs any ubuntu Linux command; login with exec"
RUN apt-get update
RUN apt-get install -y stress-ng
