apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap2
  labels:
    name: myconfigmap2
data:
  config: |-
    ---
    :verbose: true
    :environment: staged
    :pidfile: tmp/pids/mypidfile.pid
    :logfile: log/mylogfile.log
    :concurrency: 20
    :queues:
      - [default, 1]
    :dynamic: true
    :timeout: 300

