apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: bXl1c2VybmFtZQ==
  password: bXlwYXNzd29yZA==

#$ echo -n "myusername" |base64 
# bXl1c2VybmFtZQ==
#$ echo -n "mypassword"| base64
# bXlwYXNzd29yZA==
