kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-ns
  name: test-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
