kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: test-role-binding
subjects:
- kind: ServiceAccount
  name: test-account
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: test-role
  apiGroup: ""

