kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv1
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: "/mnt/data"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv2
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: "/mnt/data"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv3
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: "/mnt/data"
